CREATE TABLE "public"."itsms_20000_monitoring_measurment" (
    "process_id" varchar(200) NOT NULL,
        "id" varchar(200) NOT NULL,
    "date" date NOT NULL,
    "whattomeasure_id" int4,
	measure,
	"frequency_id" int4,
        "method_id" int4,
            "measurement_by_id" varchar(20),
        "target" text,
    "kpi_id" int4,
    "kpi_details" text,
     "eva_freq_id" int4,
        "eva_method_id" int4,
    "eva_by" text,
     "details" text, 
     "measurement_no" text,  
    "date_verify" date,
	"start" date,
	"end" date,
	"due" date,
	"result" text, 
    "target_archievement" text, 
    "details" text, 
    "date_today" date NOT NULL,
    "verification_status" varchar(200),
    "verification_failed" text,
    "scheduled" date,
    "completion" date,
     "record_group" varchar(20),
    "document" varchar(100),
    "uploaded_at" timestamptz,
    "completedby_id" varchar(20),
    "entered_by_id" int4,
    "qmsstatus_id" int8,
    "status_id" int8,
    "verification_id" int8,
 	"co_code_id" varchar(),
[i.process_id,i.id,i.date,i.whattomeasure,i.measure,i.frequency,i.method,i.measurement_by,i.target,i.kpi,i.kpi_details,i.eva_freq,i.eva_method,i.eva_by,i.details,i.measurement_no,i.date_today,i.start,i.end,i.result,i.target_archievement,i.completedby]	
    CONSTRAINT "itsms_20000_bcp_fkdey" FOREIGN KEY ("process_id") REFERENCES "public"."itsms_20000_process_map"("id"),
    CONSTRAINT "itsms_20000_bcp_fkdEey" FOREIGN KEY ("whattomeasure_id") REFERENCES "public"."itsms_20000_what_to_measure"("id"),
    CONSTRAINT "itsms_20000_bcp_fRdRkey" FOREIGN KEY ("frequency_id") REFERENCES "public"."itsms_20000_bcp_test_frequency"("id"),
    CONSTRAINT "itsms_20000_bcp_fCdVGkey" FOREIGN KEY ("method_id") REFERENCES "public"."itsms_20000_measurement_method"("id"),
    CONSTRAINT "itsms_20000_bcp_fCdVwaxcgGkey" FOREIGN KEY ("measurement_by_id") REFERENCES "public"."accounts_employees"("id"),   
    CONSTRAINT "itsms_20000_bcp_fkeWdSVy" FOREIGN KEY ("kpi_id") REFERENCES "public"."itsms_20000_kpi"("id"),
    CONSTRAINT "itsms_20000_bcp_fkedYUJMy" FOREIGN KEY ("eva_freq_id") REFERENCES "public"."itsms_20000_bcp_test_frequency"("id"),
    CONSTRAINT "itsms_20000_bcp_fAWdEkey" FOREIGN KEY ("eva_method_id") REFERENCES "public"."itsms_20000_evaluation_method"("id"),
    CONSTRAINT "itsms_20000_bcp_fQDdCkey" FOREIGN KEY ("target_archievement_id") REFERENCES "public"."itsms_20000_target_archievement"("id")
)